### ISSUE TITLE
Binding all methods

### ISSUE THREAD

**Issue by roboshoes** [hapticdata/animitter#1]
Is there a chance we could auto bind all the methods to the animitter instance? This would allow you to do things like:

``` js
var loop = animitter( render );

// and then a little later ...
setTimeout( loop.start, 1000 );
```

or when using promises:

``` js
doSomething().then( loop.start );
```

What do we think?

**Comment by roboshoes** [comment]
For now you can always do `loop.start.bind( loop )`. :worried: :hankey: :-1: :rage1:  
However, I wonder if there is any downsides with having them bound by default. :candy:

**Comment by hapticdata** [comment]
I hear you, I often do things like:

``` js
function boundAnimitter(opts){
    var loop = animitter(opts);
    return _.bindAll(loop, _.functions(loop));
}

_.extend(exports, boundAnimitter());
```

The minor drawback is just that it doesn't reuse the prototype, which is pretty inconsequential. It doesn't seem very standard but I like the idea, an alternative would be something like `animitter.bound()` doing the same. What do you think?

**Comment by roboshoes** [comment]
Yeah my biggest _"concern"_ was that it's not standard to return bound instances. I like the idea of `.bound()`.

Would allow you to do something like:

``` js
var animitter = require( "animitter" ).bound();
```

**Comment by hapticdata** [comment]
it could be either or both of these:

``` js
var animitter = require('animitter').bound; //<-- not invoked
var loop = animitter();
```

or:

``` js
var animitter = require('animitter');
//bound or bind?
var loop = animitter({ bind: true, fps: 30 });
```

**Comment by roboshoes** [comment]
I would go with the first version:

``` js
var animitter = require( "animitter" ).bound;
```

Seems the cleanest. But your call. You are god of all animitter related items.

**Comment by roboshoes** [comment]
DO IT!!

**Comment by hapticdata** [comment]
e7c2f44acb v1.1.0 has been published to npm and includes `animitter.bound([options, listener])`
